[versions]
kotlin = "1.7.20"  # Note: Plugin versions must be updated in the settings.gradle.kts too

kord-extensions = "1.5.5-20221107.093708-35"
logging = "3.0.4"
logback = "1.4.4"
github-api = "1.313"
kmongo = "4.7.1"
detekt = "1.21.0"
koma = "1.1.0"
cozy-welcome = "1.0-SNAPSHOT"
dma = "0.1.0"

[libraries]
kord-extensions = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kord-extensions" }
kord-extensions-phishing = { module = "com.kotlindiscord.kord.extensions:extra-phishing", version.ref = "kord-extensions" }
kord-extensions-pluralkit = { module = "com.kotlindiscord.kord.extensions:extra-pluralkit", version.ref = "kord-extensions"}
kord-extensions-unsafe = { module = "com.kotlindiscord.kord.extensions:unsafe", version.ref = "kord-extensions"}
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logging = { module = "io.github.microutils:kotlin-logging", version.ref = "logging" }
github-api = { module = "org.kohsuke:github-api", version.ref = "github-api" }
kmongo = { module = "org.litote.kmongo:kmongo-coroutine-serialization", version.ref = "kmongo" }
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt"}
koma = { module = "cc.ekblad:4koma", version.ref = "koma" }
cozy-welcome = {module = "org.quiltmc.community:module-welcome", version.ref = "cozy-welcome"}
dma = { module = "com.github.nocomment1105:discord-moderation-actions", version.ref = "dma"}
