[versions]
kotlin = "1.6.10"  # Note: Plugin versions must be updated in the settings.gradle.kts too

groovy = "3.0.9"
jansi = "2.4.0"
kord-extensions = "1.5.1-SNAPSHOT"
logging = "2.1.21"
logback = "1.2.8"

kotlinx-serialization = "1.3.2"
kaml = "0.38.0"

[libraries]
groovy = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
kord-extensions = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kord-extensions" }
kord-phishing = { module = "com.kotlindiscord.kord.extensions:extra-phishing", version.ref = "kord-extensions" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logging = { module = "io.github.microutils:kotlin-logging", version.ref = "logging" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kaml = { module = "com.charleskorn.kaml:kaml", version.ref = "kaml" }