[versions]
kotlin = "1.6.10"  # Note: Plugin versions must be updated in the settings.gradle.kts too

groovy = "3.0.9"
kord-extensions = "1.5.2-20220308.163313-32"
logging = "2.1.21"
logback = "1.2.8"
toml-reader = "1.2"
github-api = "1.303"
kmongo = "4.5.0"

[libraries]
groovy = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
kord-extensions = { module = "com.kotlindiscord.kord.extensions:kord-extensions", version.ref = "kord-extensions" }
kord-phishing = { module = "com.kotlindiscord.kord.extensions:extra-phishing", version.ref = "kord-extensions" }
kord-mappings = { module = "com.kotlindiscord.kord.extensions:extra-mappings", version.ref = "kord-extensions"}
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logging = { module = "io.github.microutils:kotlin-logging", version.ref = "logging" }
toml = { module = "com.github.jezza:toml", version.ref = "toml-reader"}
github-api = { module = "org.kohsuke:github-api", version.ref = "github-api"}
kmongo = {module = "org.litote.kmongo:kmongo-coroutine-serialization", version.ref = "kmongo"}