# An included configuration file for Lily, used for the instance running in the Iris Discord server.

# Specify the path to this file in the CONFIG_FILE field of your .env file if you would like to use it.

activity = "Iris"

[[command]]
name = "shader-config"
help = "Informs the user of Shader Config issues."
title = "You can't currently edit shader settings."
description = """
The shader configuration menu is currently in development, and is being publicly tested.
• Progress updates can be found in <#774354933436645478>
• Test builds, once available, can be found in <#883067831485366304>
• Full releases will be announced in <#817181278931517453>
Please do not ask for an ETA on this or any other feature."""

[[command]]
name = "nec"
help = "Informs the user of issues with Not Enough Crashes."
title = "Remove Not Enough Crashes from your mods folder."
description = "Not Enough Crashes (NEC) is well know to cause issues and often makes the debugging process more difficult. A good alternative is Crafty Crashes (https://github.com/Chocohead/Crafty-Crashes/releases/tag/v1.0)\nIf you had previously sent a log or crash report please remove NEC, recreate the issue, and resend the relevant files if the issue persists."

[[command]]
name = "crash-report"
help = "Informs the user of how to get a crash report."
title = "How to get crash reports:"
description = "Crash reports can be found in the `crash-reports` sub-directory in `.minecraft` on clients, or the crash-reports sub-directory of the server directory for servers. We're probably interested in the most recent file, which you can drag and drop into Discord."

[[command]]
name = "pbr"
help = "Informs the user about PBR issues"
title = "Iris doesn't currently support PBR."
description = "Resource pack PBR support is a complicated feature to implement and our dev team currently have other priorities. Support will be coming in a future version. In the meantime, the Complementary shader pack has an integrated PBR (iPBR) that works with Iris."

[[command]]
name = "eta"
help = "Informs the user of the ETA"
title = "What's the ETA?!?"
description = "Some time between now and the heat death of the universe. In short, we don't know!"

[[command]]
name = "indium"
help = "Informs the user of the need to use Indium."
title = "You may need Indium for some mods' features to work."
description = "Indium is a minecraft mod that adds Fabric Rendering API (FRAPI) support to Sodium. It can be required for many mods, such as Connected Texture mods and Campanion. It can be found at this link: (<https://modrinth.com/mod/Indium>)"

[[command]]
name = "logs"
help = "Informs the user of how to get a log file."
title = "How to get a log file:"
description = "Game logs can be found in the `logs` sub-directory in .minecraft on clients, or the `logs` sub-folder of the server directory for servers. We're probably interested in the file named `latest.log`, which you can drag and drop into Discord."

[[command]]
name = "rule"

[[command.subcommand]]
name = "1"
help = "Reminds the user of Rule 1: Be decent to one another."
title = "Rule 1"
description = "Be decent to one another. We're all human. Any and all forms of bigotry, harassment, doxxing, exclusionary, or otherwise abusive behavior will not be tolerated. Excessive rudeness, impatience, and hostility are not welcome. Do not rage out or make personal attacks against other people. Do not encourage users to brigade/raid other communities."

[[command.subcommand]]
name = "2"
help = "Reminds the user of Rule 2: Keep chat clean."
title = "Rule 2"
description = "Keep chat clean. Do not spam text, images, user mentions, emojis, reactions, or anything else. Do not post offensive, obscene, politically charged, or sexually explicit content. Avoid using vulgar language and excessive profanity. Use English at all times in public channels."

[[command.subcommand]]
name = "3"
help = "Reminds the user of Rule 3: Keep discussion on-topic."
title = "Rule 3"
description = "Keep discussion on-topic. This server is focused around Iris. General chatter unrelated to Iris is best kept to other Discord communities or to DMs."

[[command.subcommand]]
name = "4"
help = "Reminds the user of Rule 4: Understand that support is not guaranteed."
title = "Rule 4"
description = "Understand that support is not guaranteed. Support will be provided on a best-effort basis."

[[command.subcommand]]
name = "5"
help = "Reminds the user of Rule 5: Do not ask for support on compiling Iris."
title = "Rule 5"
description = "Do not ask for support on compiling Iris, and refrain from providing this support. There is sufficient information for people who know what they're doing to compile the mod themselves without help. If we would like you to use a given version of the mod, we will give you a compiled build of that version."

[[command.subcommand]]
name = "6"
help = "Reminds the user of Rule 6: No links to executable files."
title = "Rule 6"
description = "No links to executable files or JAR files. Uploading or directly linking to executable files is not allowed without prior approval."

[[command.subcommand]]
name = "7"
help = "Reminds the user of Rule 7: Refrain from sending unsolicited pings and DMs."
title = "Rule 7"
description = "Refrain from sending unsolicited pings and direct messages. Pings and DMs can be annoying to deal with, so please avoid using them unless they are necessary. Use pings in replies with discretion as well. Unsolicited support requests made with pings and DMs are a big no."

[[command.subcommand]]
name = "8"
help = "Reminds the user of Rule 8: Adhere to the Discord Terms of Service."
title = "Rule 8"
description = "Adhere to the Discord Terms of Service. I'd like to avoid getting this community banned. No piracy! Absolutely no support will be provided for people running cracked versions of the game. Providing support for these people counts as a rule violation!"

[[command.subcommand]]
name = "9"
help = "Reminds the user of Rule 9: Don't recommend unofficial forks of Iris to people in support channels."
title = "Rule 9"
description = "Do not recommend unofficial forks or ports of Iris to people in the support channels, and do not use the support channels to ask about forks or ports of Iris. We do not provide support for these forks or ports, and they've been a big source of headaches for our support team. Trying to circumvent this rule by telling people to move to DMs or to non-support channels to talk about these forks or ports is still a violation of this rule. This rule was created because people constantly recommended broken Iris forks to people who probably shouldn't be using them in the support channels."

[[command]]
name = "shader-editing"
help = "Informs the user about manual shader editing."
title = "Manual shader editing is unsupported."
description = """
Due to Iris's shader configuration currently being in Patreon-only beta, some users have resorted to manually editing the files of the shader. This can cause hard-to-resolve issues for users, support team members, and shader developers. In addition, settings files are easily transferable between versions whereas manual shader editing is not.
No support will be provided by staff for problems that occur as a result of this process. Please refrain from recommending manual shader editing.
The shader configuration menu is currently in development. Please use /shader-config for more information."""

[[command]]
name = "sodium"
help = "Provides the user with information about Sodium."
title = "Information About Sodium"
description = """
Sodium is a Fabric mod created by JellySquid & CaffeineMC that allows Iris to get its stellar performance.

 Iris no longer bundles Sodium. The installer automatically downloads both Iris and Sodium. If you downloaded Iris independently, you need to download Sodium and place it in your mods folder along with Iris. You can download Sodium from (https://modrinth.com/mod/sodium)"""

[[command]]
name = "starline"
help = "Informs the use of the lack of Starline support."
title = "Starline is not supported."
description = "Starline is an unofficial fork and not supported by us, please do not ask the support team for help with it."

[[command]]
name = "updatedrivers"

[[command.subcommand]]
name = "amd"
help = "Informs the user that they should try to update their AMD Radeon drivers"
title = "Update your AMD Radeon Drivers"
description = "You can use AMD's Radeon Software to easily update your drivers, If you don't have it, download it here: https://www.amd.com/en/support"

[[command.subcommand]]
name = "nvidia"
help = "Informs the user that they should try to update their Nvidia drivers"
title = "Update your Nvidia Drivers"
description = "You can use Nvidia GeForce Experience to easily update drivers, If you don't have it, download it here: https://www.nvidia.com/Download/index.aspx?lang=us"

[[command.subcommand]]
name = "intel"
help = "Informs the user that they should try to update their Intel drivers"
title = "Update your Intel Drivers"
description = "You can use Intel DSA to easily update your drivers, If you don't have it, download it here: https://www.intel.com/content/www/us/en/support/detect.html"

[[command.subcommand]]
name = "ddu"
help = "Informs the user about DDU"
title = "Using DDU is an alternative way to update / reinstall malfunctioning drivers."
description = """
You can use DDU to clean up any issues that your drivers may have had when installing. Here are the steps that you take:
1) Download your drivers manually
2) Boot into Safe mode
3) DDU the driver
4) Install the driver from the manually downloaded installer in Step 1
5) Boot back into normal mode."""

[[command]]
name = "optifine"

[[command.subcommand]]
name = "cem"
help = "Informs the user about how to get OptiFine's Custom Entity Models"
title = "Custom Entity Models"
description = "CEM is a fabric mod that allows for OptiFine's custom entity models! It can be found here: (<https://www.curseforge.com/minecraft/mc-mods/custom-entity-models-cem>)"

[[command.subcommand]]
name = "ctm"
help = "Informs the user about how to get OptiFine's Connected Textures"
title = "Connected textures"
description = "Continuity is a fabric mod allowing for OptiFine's connected textures! It can be found here: (<https://modrinth.com/mod/continuity/>)"

[[command.subcommand]]
name = "zoom"
help = "Informs the user about how to get OptiFine's Zoom"
title = "Zoom"
description = "OKZoomer is a fabric mod allowing for OptiFine's zoom! It can be found here: (<https://modrinth.com/mod/ok-zoomer>)"

[[command.subcommand]]
name = "cit"
help = "Informs the user about how to get OptiFine's Custom Item Textures"
title = "Custom Item Textures"
description = "CIT Resewn is a fabric mod allowing for OptiFine's custom item textures! Make sure to enable \"Broken paths\" in the config. It can be found here: (<https://modrinth.com/mod/cit-resewn>) "

[[command.subcommand]]
name = "cc"
help = "Informs the user about how to get OptiFine's Chunk Caching"
title = "Chunk Caching"
description = "Bobby is a fabric mod allowing for OptiFine's chunk caching! It can be found here: (<https://modrinth.com/mod/bobby>)"

[[command.subcommand]]
name = "dl"
help = "Informs the user about how to get OptiFine's Dynamic Lights"
title = "Dynamic Lights"
description = "LambDynamicLights is a fabric mod allowing for OptiFine's dynamic lights! It can be found here (<https://modrinth.com/mod/lambdynamiclights>)"

[[command.subcommand]]
name = "sl"
help = "Informs the user about how to get OptiFine's Smart Leaves"
title = "Smart Leaves"
description = "Cull Leaves is a fabric mod allowing for OptiFine's smart leaves! It can be found here (<https://modrinth.com/mod/cull-leaves>)"

[[command.subcommand]]
name = "es"
help = "Informs the user about how to get OptiFine's Extra Settings"
title = "Extra Settings"
description = "Sodium Extras is a fabric mod allowing for OptiFine's extra settings! It can be found here (<https://modrinth.com/mod/sodium-extra>)"

[[command.subcommand]]
name = "anim"
help = "Informs the user about how to get OptiFine's Animated mods, armors, and GUIs"
title = "Animations"
description = "Animatica is a fabric mod allowing for OptiFine's animations! It can be found here (<https://modrinth.com/mod/animatica>)"

[[command.subcommand]]
name = "bg"
help = "Informs the user about how to get OptiFine's Better Grass"
title = "Better Grass"
description = "LambdaBetterGrass is a fabric mod allowing for OptiFine's better grass! It can be found here (<https://modrinth.com/mod/lambdabettergrass>)"

[[command]]
name = "rtx"
help = "Informs the user about the differences between Ray Tracing, Path Tracing, and RTX."
title = "What are Ray Tracing, Path Tracing, and RTX?"
description = """
**Ray Tracing**
Ray tracing refers to a family of techniques revolving around sending rays out into the world and then doing things with them. Common usage of ray tracing techniques include: screen space reflections on things like water (specifically ray marching) and finding hit locations in shooter games (specifically ray casting).
**Path Tracing**
Path tracing is an advanced type of ray tracing which can be used to create lighting which behaves almost exactly like real life. It calculates paths (hence the name) that light can take from a source to your eyes.
**RTX**
RTX is Nvidia's line of graphics cards which have hardware dedicated to doing a lot of ray tracing very quickly. AMD's newest graphics cards also have equivalent hardware, but they don't have a fancy name for it. Minecraft Java Edition doesn't currently have the capabilities required to use this hardware though, so while all techniques mentioned above can be used in Java Edition, they will run at normal speed instead of turbo speed."""

[[command]]
name = "jarfix"
help = "Informs the user on what Jarfix is and how to use it"
title = "What is Jarfix and how does it help?"
description = "Jarfix is a tool that can be used to fix issues where .jar files don't launch, due to their associations being hijacked, on double-click. You can download it from https://johann.loefflmann.net/downloads/jarfix.exe"

[[command]]
name = "snapshots"
help = "Informs the user about where to find snapshot builds"
title = "Where can I find snapshot builds?"
description = """
Snapshot, pre-release, and release candidate builds, when available, can be found on GitHub at https://github.com/IrisShaders/Iris/releases. You can also compile a build yourself from https://github.com/IrisShaders/Iris/tree/1.18. Per rule 5, no support will be provided with compiling Iris. Builds will also occasionally be posted in <#883067831485366304>.  Snapshot, pre-release, and release candidate builds are also sometimes made available to Patreon supporters early.

 **Do not ask for an ETA on when Iris will update.**"""

[[command]]
name = "performance"
help = "Informs the user about how to improve performance when running Minecraft"
title = "Minecraft has extremely variable performance."
description = "There's only a handful of things the support team can suggest to improve FPS/performance:\n\n- Optimize in-game settings (lower render distance, screen resolution etc.)\n- Install performance mods (<https://lambdaurora.dev/optifine_alternatives/>)\n- Allocate an appropriate amount of RAM (4GB for 1.18+, 3GB for 1.17 and below)\n- Optimize system settings (power settings for Windows etc.)\n- Upgrade your hardware\n\nOther than the above advice, there is very little the support team can suggest to improve your performance. **If you're experiencing lower performance on newer versions, that's expected behaviour and there's nothing that can be done.**"
