[versions]
# Plugins
kotlin = "2.3.0"
detekt = "1.23.8"
git-hooks = "0.0.2"
grgit = "5.3.0"
blossom = "2.1.0"

# Libraries
kord-extensions = "2.4.1-20251224.130127-1"
kordex-plugin = "1.9.0"
kordex-i18n = "1.1.1"
logging = "7.0.14"
logback = "1.5.24"
logback-groovy = "1.14.5"
github-api = "1.330"
kmongo = "5.5.1"
docgenerator = "0.3.2"
groovy = "3.0.25"
jansi = "2.4.2"
ktor = "3.4.0"

[libraries]
kord-extensions-core = { module = "dev.kordex:kord-extensions", version.ref = "kord-extensions" }
kord-extensions-phishing = { module = "dev.kordex.modules:func-phishing", version.ref = "kord-extensions" }
kord-extensions-pluralkit = { module = "dev.kordex.modules:pluralkit", version.ref = "kord-extensions" }
kord-extensions-unsafe = { module = "dev.kordex.modules:dev-unsafe", version.ref = "kord-extensions" }
kord-extensions-welcome = { module = "dev.kordex.modules:func-welcome", version.ref = "kord-extensions" }

groovy = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-groovy = { module = "io.github.virtualdogbert:logback-groovy-config", version.ref = "logback-groovy" }
logging = { module = "io.github.oshai:kotlin-logging", version.ref = "logging" }
github-api = { module = "org.kohsuke:github-api", version.ref = "github-api" }
kmongo = { module = "org.litote.kmongo:kmongo-coroutine-serialization", version.ref = "kmongo" }
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
docgenerator = { module = "org.hyacinthbots:doc-generator", version.ref = "docgenerator" }
ktor-java = { module = "io.ktor:ktor-client-java", version.ref = "ktor" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
git-hooks = { id = "com.github.jakemarsden.git-hooks", version.ref = "git-hooks" }
grgit = { id = "org.ajoberstar.grgit", version.ref = "grgit" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
kord-extensions-plugin = { id = "dev.kordex.gradle.kordex", version.ref = "kordex-plugin" }
kord-extensions-i18n = { id = "dev.kordex.gradle.i18n", version.ref = "kordex-i18n" }
